### ISSUE TITLE
Translate mapa into belarussian language.

### ISSUE THREAD

**Issue by fr0zen** [diglabby/mapa#1]
Translate needed to succesfully launch mapa in belarus.

**Comment by fr0zen** [comment]
Steps for success complete.

- [ ]  Create our version of https://github.com/goodmap/goodmap/blob/master/src/locales/translation-en.json translation-be.json
- [ ]  Translate texts into belarusian language with our local adaptations.
- [ ] Translation proofreading
- [ ] Include translation file into project
- [ ] Rebuild project
- [ ] Final proofreading. Check if everthing on it's place.

**Comment by rizomaa** [comment]
[BYloc(be).zip](https://github.com/diglabby/mapa/files/3388744/BYloc.be.zip)

**Comment by wellemut** [comment]
Here is the issue on our side, which I will close now: https://github.com/goodmap/goodmap-old/issues/519

**Comment by rizomaa** [comment]
For Kseniya,

1. Take the file https://github.com/diglabby/mapa/files/3388744/BYloc.be.zip
2. Unpack this file.
3. Rename this file to belarusianLocale.txt
4. Make clone of your repo https://github.com/KsenjaV/
5. Overwrite this existing file with a new version of belarusianLocale.txt
6. After make `git commit -am "last changes"`
7. After add `git pull `
8. `Git push `

**Comment by wellemut** [comment]
Is this the same: https://github.com/diglabby/mapa/issues/5 "As a user, I want to have translation of the Mapa-interface on belarusian and english languages"?

**Comment by rizomaa** [comment]
> Is this the same: #5 "As a user, I want to have translation of the Mapa-interface on belarusian and english languages"?

Yes, the same, maybe more  practical oriented
