### ISSUE TITLE
[5][1] Add + button with menu

### ISSUE THREAD

**Issue by rizomaa** [diglabby/mapa#102]

**Comment by rizomaa** [comment]
@SaintNekit any issues around this? do you need help?

**Comment by rizomaa** [comment]
@SaintNekit @dmitrap guys I added @tragladit to this task please be responsible to his questions due t oour need to move forward and the task is bottle neck

**Comment by wellemut** [comment]
If it is about this button, I would prefer to have it in the same size and style (black symbole, white background) as the others...
Is it on purpose the other way round?

![grafik](https://user-images.githubusercontent.com/15019030/67042348-fbadca00-f127-11e9-83b2-22fddae11ea3.png)

**Comment by rizomaa** [comment]
task is done.
