### ISSUE TITLE
[NN] BY, EN: Add new entry form - Creative-Commons License CC0 link goes to DE license text

### ISSUE THREAD

**Issue by antos-k** [diglabby/mapa#104]
1. Choose BY or EN language
2. Go to map
3. Press  Add new entry button
4. Go to the bottom of the form
5. Check  Creative-Commons License CC0

**Result:** 'Creative-Commons License CC0' link goes to DE license: https://creativecommons.org/publicdomain/zero/1.0/deed.de
**Expected result:** Link should go to license translation according current language of interface:
https://creativecommons.org/publicdomain/zero/1.0/deed.be for BY interface
https://creativecommons.org/publicdomain/zero/1.0/deed.en for EN interface

EN issue screenshot:
![Screenshot at 2019-08-14 10-01-55](https://user-images.githubusercontent.com/53947213/63003613-37ef5080-be81-11e9-97b6-e2f1ed336420.png)

**Comment by rizomaa** [comment]
@dmitrap 

please use for 

Belarusian version; https://creativecommons.org/publicdomain/zero/1.0/deed.be
And for English:  https://creativecommons.org/publicdomain/zero/1.0/deed.en

**Comment by antos-k** [comment]
Fixed

**Comment by antos-k** [comment]
Done and tested
