### ISSUE TITLE
[5][5] Choose existing fields for your iframe code

### ISSUE THREAD

**Issue by rizomaa** [diglabby/mapa#108]
- hashtag
- width
- height

**Comment by wellemut** [comment]
In the session with Damian we decided that the hashtag will be chosen in
the search field before you open the sharing field.
That is already working.

My suggestion is to remove the tag field in the sharing pop-up. Other
things just confuse the user...

Helmut Wolman

(mailed on the move)
Mobil: 0049-15734448245
Mannheim

Mister Cable <notifications@github.com> schrieb am Mi., 14. Aug. 2019,
11:04:

**Comment by rizomaa** [comment]
@JustOneJance  What is the status of the issue

what do you think about @wellemut idea?

**Comment by k-gorod** [comment]
Can u explain please what it is mean "ifame code"? What we talking about?

**Comment by rizomaa** [comment]
Please look at the screenshot.
![Selection_057](https://user-images.githubusercontent.com/9870374/84598755-b63bcb00-ae75-11ea-9743-62bd976facf3.png)

 There is a menu on the right side of the Mapa web-app

**Comment by chizhovm** [comment]
На дадзены момант віджэт выглядае так:
![issue109](https://user-images.githubusercontent.com/47754077/87850300-be18e000-c8f7-11ea-9d7d-58bbe1eaed02.jpg)
Ці патрэбна рабіць штосьці яшчэ?

**Comment by rizomaa** [comment]
Тут пазначыў дэталі што змяніць ў віджэце. лепей працягнуць у асобнай задачы, бо гэта называецца іначай 
https://github.com/diglabby/mapa/issues/405

Па гэтай усё
