### ISSUE TITLE
[NN] BY, EN - map navigation buttons hints are not translatet according current language

### ISSUE THREAD

**Issue by antos-k** [diglabby/mapa#110]
1. Choose BY or EN language
2. Go to map
3. Hover buttons at the right bottom corner of map

**Result:** There are next hints not depending of the current interface language: 'Zeige meine Position' , ' Zoom in', 'Zoom out'
**Expected result:** Hints should be translated according current language of interface.
Notice: It seems this translations can be somewhere outside translation-be.json / translation-en.json

BY issue screenshot:
![BY map button hint Zeige meine position](https://user-images.githubusercontent.com/53947213/63005964-383e1a80-be86-11e9-8582-47c138eb5502.png)

**Comment by ksandrsis** [comment]
done navigation button
