### ISSUE TITLE
[GDB8] Discuss tags to category mapping

### ISSUE THREAD

**Issue by simonline** [diglabby/mapa#113]

**Comment by wellemut** [comment]
This relates to the question about map-icons and map-legend: https://github.com/goodmap/goodmap-old/issues/307

A first draft of categories for tags was started here: https://docs.google.com/spreadsheets/d/1nG6rAHAIEZrnei_7X3jwoYbTNahaAYPdng_w8qGlmoM/edit#gid=568640820

**Comment by intergalacticsuperhero** [comment]
There are suggestions for the most relevant tags by Kartevonmorgen:
http://blog.vonmorgen.org/piloten/

**Comment by intergalacticsuperhero** [comment]
I downloaded all Tags used by kartevonmorgen (without the number of times that a tag has been used)
[tags_kartevonmorgen.zip](https://github.com/diglabby/mapa/files/3504818/tags_kartevonmorgen.zip)

**Comment by intergalacticsuperhero** [comment]
I created a spreadsheet for mapping the 100 most relevant KvM tags to WECHANGE categories:
https://docs.google.com/spreadsheets/d/1dBg2qGArQMWDI2ey3713cdjHp-Ia4OEzXtFjHCWVVXE/edit#gid=0

**Comment by intergalacticsuperhero** [comment]
Result:
* create filter service that transforms the tags of KvM Places / Events to WECHANGE categories
* Implementation of a Django / Python web application (preferred)

**Comment by intergalacticsuperhero** [comment]
#143
