### ISSUE TITLE
EN wrong translations/untranslated

### ISSUE THREAD

**Issue by antos-k** [diglabby/mapa#117]
Now|Expected|Where
-------|---------|-----------
Karte von morgen| Map of tomorrow| EN title of the page
How to use the von morgen map|How to use the map of tomorrow|EN homepage
so Mapai: - increased transparency... - deepening the interaction...- Create ...|so Map can help to: - increase... - deep... - create| EN homepage
citizens - finding initiatives, similar in values ​​and **vluchatstsa** in their activities.| citizens - finding initiatives, similar in values ​​and participate in their activities.| Homepage - We have a vision
1.Hackathon work together activists and aytsivalantsorav. | and IT-volunteers | EN homepage - How it works / Offline
3.Educational lectures on **aopensors** and community interaction.| opensource and community interaction | EN homepage - How it works / Offline
Запоўні анкету! | Fill the application form! | EN Homepage = Our partners (application button 'class="pure-button team-button" ')
Write us for any queations | Write us for any questions | How to contact us
city Minsk, st.З.Buadyli, 3, ap.2Н ('Фаланстэр') | city Minsk, Zm.Buadyli str., 3, ap.2N ('Falanster') | How to contact us - You can find us on address:
![button](https://user-images.githubusercontent.com/53947213/63017496-2a48c380-be9f-11e9-9c30-7b3738318465.png)
![pagetitle](https://user-images.githubusercontent.com/53947213/63017840-ff12a400-be9f-11e9-933e-bb6f7e0e8300.png)
![EN_Contact Us](https://user-images.githubusercontent.com/53947213/63017500-2ae15a00-be9f-11e9-8d36-141f2df12242.png)
![EN - to use the von morgen map](https://user-images.githubusercontent.com/53947213/63017502-2b79f080-be9f-11e9-9281-6cd53dd8eced.png)
![How it works - Offline](https://user-images.githubusercontent.com/53947213/63017503-2c128700-be9f-11e9-8a8d-58418b07f661.png)
![EN_Vision](https://user-images.githubusercontent.com/53947213/63017590-6ed45f00-be9f-11e9-9bbb-4eff58426736.png)

**Comment by ksandrsis** [comment]
title is not in JSON

**Comment by ksandrsis** [comment]
Button  ''Запоўні анкету!'' is not in JSON

**Comment by ksandrsis** [comment]
All other mistakes fixed
