### ISSUE TITLE
BY wrong translations/untranslated

### ISSUE THREAD

**Issue by antos-k** [diglabby/mapa#118]
Now|Expected|Where
-------|---------|-----------
Karte von morgen| Мапа заўтрашняга дня | BY title of the page
3.Асветніцкія лекцыі па аопенсорс і ўзаемадзеянні супольнасцяў.| опенсорс | BY homepage - How it works / Offline
Нашых партнёры | Як удзельнічаць | BY homepage - Partners
мы будзем удзячны за вашы водгукі | будзем удзячныя за вашыя водгукі | Contact us
Мной прачытаны і прыняты умовы | Я прачытаў і прымаю умовы | Map - Add new entry - Licension

![pagetitle](https://user-images.githubusercontent.com/53947213/63020431-c88c5780-bea6-11e9-9e88-1201a77de188.png)
![BY for who](https://user-images.githubusercontent.com/53947213/63019016-efe12580-bea2-11e9-9d1e-ad2f4e2c306f.png)
![BY_umovy](https://user-images.githubusercontent.com/53947213/63019017-f079bc00-bea2-11e9-9bc3-db42f53e5286.png)

**Comment by ksandrsis** [comment]
title not in JSON , all other done
