### ISSUE TITLE
Define categories for initiatives (in KVM?) 

### ISSUE THREAD

**Issue by simonline** [diglabby/mapa#124]

**Comment by wellemut** [comment]
@simonline Please share the link where to find this Mircroservice and move the card to the last colum... 
Its basically done I think

**Comment by wellemut** [comment]
Here is the „Microservice“ from Simon and Markus, (its an „Adapter“ for „GoodDB“). 
The Goal is to have an exchange-Sercie for organisations and events on kvm/mapa and wechange. This Adapter translates   Tags to Categories, before they are added to GoodDB


- Repository: https://github.com/wechange-eg/gooddb-adapter-tags
- Data: https://github.com/wechange-eg/gooddb-adapter-tags/blob/master/core/fixtures/core.json (ggf. nicht mehr aktuell, da Tags im Backend des Service verwaltet werden können)
- API (yaml): https://github.com/goodmap/goodmap-db/blob/master/GoodDB-API.yaml
- API (Swagger): https://app.swaggerhub.com/api/WECHANGE-eG/GoodDBAdapter/0.0.2 
- Produktiv-System: https://gooddb-adapter-tags.wechange.de/api/v1/places

**Comment by rizomaa** [comment]
@simonline do you have any updates around the issue.

We also want to start discussion about categories. Because many organisation tasked the feature. 

But I'm still in consideration about the moment to add this feature for Belarus. @wellemut

**Comment by rizomaa** [comment]
@wellemut @simonline what is the status of your project?

**Comment by wellemut** [comment]
Instead of categories we use the glossary of change: glossardeswandels.de/
Similar hashtags are grouped there under one term

Categories so far is just needed for certain networks. In those cases we create a page with an iframe that has a name lik name="if_kvm" and than we can build links and buttons around the mapp with target="if_kvm"

Workaround, but everybody is happy so far.

**Comment by rizomaa** [comment]
"that has a name lik name="if_kvm" and than we can build links and buttons around the mapp with target="if_kvm"" I'm confused with the phrase. could you paraphrase this? @wellemut

**Comment by wellemut** [comment]
You can give a name to an iframe. and in the target-command of the url you can make it open in that iframe, instead of a new tab or so.

You can all it nem="map-iframe" and when you say target="map-iframe" then the link opens in the iframe on the same page.

**Comment by rizomaa** [comment]
@wellemut thanks,
If to follow you link in previous post it becomes clear.
