### ISSUE TITLE
[4.2] Get entries from openfairDB

### ISSUE THREAD

**Issue by rizomaa** [diglabby/mapa#126]
- by a type of subscription ?
- by date of last update?
-

**Comment by uklotzde** [comment]
Some ideas that came into my mind:
- Use the new OpenFairDB endpoint [GET /entry/recently-changed](https://github.com/slowtec/openfairdb/pull/199) that will be available soon. If you need additional functionality lets discuss.
- Pull the latest changes periodically, i.e. hourly or once a day
- Sort the results into buckets in your local database: daily (e.g. last 6 days), weekly (e.g. last 4 weeks), and last month
- Periodically process the subscriptions: Determine the relevant buckets with collected changes and filter them according to the subscription (bbox, category, ...)
- Compose an e-mail with a summary and send it out by using an external e-mail service

We should've done this decomposition into microservices earlier! I'm curious to see your results :)

**Comment by Asteur** [comment]
GET /entries/recently-changed will help us

**Comment by KonstantinKudelko** [comment]
Closed by https://github.com/diglabby/mapa-subscription/pull/3
