### ISSUE TITLE
[4.7] Setup Subscription table structure

### ISSUE THREAD

**Issue by rizomaa** [diglabby/mapa#129]

**Comment by Asteur** [comment]
set sqlite3
create 2 tables

CREATE TABLE "subs_types" ( `id` INTEGER PRIMARY KEY AUTOINCREMENT, `name` varchar ( 3 ) )

CREATE TABLE "subscriptions” ( `email` TEXT NOT NULL, `hash` text NOT NULL, `type_id` integer NOT NULL, `last_date` INTEGER, `subs_param` blob NOT NULL, PRIMARY KEY(`hash`), FOREIGN KEY(`type_id`) REFERENCES `subs_types`(`id`) )

**Comment by Asteur** [comment]
[subscriptions.db.zip](https://github.com/diglabby/mapa/files/3504766/subscriptions.db.zip)

**Comment by KonstantinKudelko** [comment]
Closed by diglabby/mapa-subscription#3
