### ISSUE TITLE
[4.9] Form data for the mail template

### ISSUE THREAD

**Issue by rizomaa** [diglabby/mapa#133]
- ini
- tag
- geo

**Comment by rizomaa** [comment]
To create array for delivery message (array to string) 
to mark a tag name on an item list.
to add unsubscription links for each group or separate items

**Comment by Asteur** [comment]
Mailing process for script:
- Get [recent for the period] from API 
(http://dev.ofdb.io/v0/entries/recently-changed?since=1565647200&until=1565733600&offset=0&limit=100)

- Get [distinct emails] from subscriptions (subscriptions.db)
- for email in [distinct emails]
    - Prepare lists for mailing:
    - list_with_entries_to_send = [], subs_by_entries = []
    - list_with_area_to_send = [], subs_by_areas = []
    - list_with_tag_area_to_send = [], subs_by_tag_areas = []


    - Get rows with data from subscriptions | by email
    - For row in rows:
        - Check type of subscription in row
        - If type == ‘I’
            - Add to subs_by_entries
        - If type == ‘G’
            - Add to subs_by_areas
        - If type == ‘TG’
            - Add to subs_by_tag_areas

    - If subs_by_entries
        - For sub in subs_by_entries
            - Add data to [list_with_entries_to_send] from [recent for the period] by id
    - If subs_by_areas
        - For sub in subs_by_areas
            - Add data to [list_with_area_to_send] from [recent for the period] by coordinates(iterate by [recent for the period] and check if row is in coordinates square)
    - If subs_by_tag_areas
        - For sub in subs_by_tag_areas
            - Add data to [list_with_tag_area_to_send] from [recent for the period] by coordinates and tags (iterate by [recent for the period] and check if the row is in coordinates and have the necessary hashtag)

    - For subs_by_entries
        - Add entries to TEMPLATE
        - Add unsubscribe LINK to TEMPLATE
    - For subs_by_areas
        - Add entries to TEMPLATE
        - Add unsubscribe LINK to TEMPLATE
    - For subs_by_tag_areas
        - Add entries to TEMPLATE
        - Add unsubscribe LINK to TEMPLATE

    - Send TEMPLATE
        - Update date in [subscriptions.db]

**Comment by KonstantinKudelko** [comment]
Close regarding https://github.com/diglabby/mapa-subscription/pull/4

**Comment by rizomaa** [comment]
@Asteur 

https://falanster.slack.com/files/U16B65D6W/FMBQCUQHW/image20190813_173616324.jpg
