### ISSUE TITLE
[NN] Hide rating from initiatives card

### ISSUE THREAD

**Issue by rizomaa** [diglabby/mapa#138]
1. Hide from list page (flower)
2. Hide from initiative page (add button, all comments with rating system)
![Selection_037](https://user-images.githubusercontent.com/9870374/63083024-5e2ff180-bf50-11e9-966a-703de83c559f.png)
![Selection_035](https://user-images.githubusercontent.com/9870374/63083037-64be6900-bf50-11e9-952d-73a956577748.png)

**Comment by Anthony-Hoopkins** [comment]
Done dev

**Comment by rizomaa** [comment]
@Anthony-Hoopkins do you mean we need to move to test the issue?
where is the pull request relating the task?

**Comment by Anthony-Hoopkins** [comment]
https://github.com/diglabby/mapa/pull/140

**Comment by rizomaa** [comment]
@Anthony-Hoopkins please tag @antos-k when it is ready to test 
@fr0zen
