### ISSUE TITLE
[GDB9] Create tag mapping microservice based of filter API

### ISSUE THREAD

**Issue by intergalacticsuperhero** [diglabby/mapa#143]
* Django / Python web app

**Comment by intergalacticsuperhero** [comment]
* Python 3.6 (mit pyenv)
* pipenv (Package installer for python)
* Django (install via pipenv, current version)
* Django REST framework

**Comment by wellemut** [comment]
Check out the service from @elbotho https://vm-backend.netlify.com/#/tags

Source: https://github.com/goodmap/goodmap-old/issues/375#issuecomment-437687309

**Comment by wellemut** [comment]
What if we include this microservice of mapping tags to categories (https://github.com/diglabby/mapa/issues/113) in the Glossary of change? 

Than we only need one point to moderate tags from the viewpoint of kvm
