### ISSUE TITLE
Create/edit event - FE input validation is missed for start/end dates

### ISSUE THREAD

**Issue by antos-k** [diglabby/mapa#147]
1. Open map
2. Press 'Add new entry' (or edit existing event)
3. Select 'Event' category (Start/end datepickers appears)
4. Select any correct dates using datepickers
5. Change (in a-d cases by manual editing of field) date next way: 
a. incorrect values with letters or symbols, for example 'quer ty!'
b. unexisting dates, for example, '2019-13-44'
c. correct dates, but end date is earlier than start date
d. date(s) before today
e. correct dates, but end date is earlier than start date - **by clicking on datepicker**
6. Fill other fields correctly and  press Save

**Results:**
a., b. Server error (422).
c., e. Server error (400).
d. Saved successfully. 

**Expected:** Only correct periods should be allowed. So we need input validation. Or (fastfix of a-d)  we can allow dates choosing only by datepicker (deny manual editing of field), but case e. will need a separate fix (now start and date have no relations between it - realised as separate datepickers).

**To be discussed:** Is case d. current behavior incorrect, or we should allow to set dates in the past when we create event? When edit the event (it can be already in process or finished)?

![incorrect date](https://user-images.githubusercontent.com/53947213/63117082-c0fea880-bfa3-11e9-8b59-048413376525.png)
![unexisting dates](https://user-images.githubusercontent.com/53947213/63117083-c0fea880-bfa3-11e9-9d50-23344b68c885.png)
![End before start](https://user-images.githubusercontent.com/53947213/63117081-c0fea880-bfa3-11e9-992c-45ca7c1235a9.png)

**Comment by Anthony-Hoopkins** [comment]
https://github.com/diglabby/mapa/pull/172

**Comment by rizomaa** [comment]
@Anthony-Hoopkins could we close the issue?
