### ISSUE TITLE
Add BY text to the technical pages (JS required, incorrect url)

### ISSUE THREAD

**Issue by antos-k** [diglabby/mapa#154]
a.
1. Disable javascript in browser or ublock/adblock settings
2. Open map

**Result:** Page with only DE and EN messages appears.

**Expected** Page with DE, EN and BY messages appears. BY message: 'Гэтая старонка патрабуе JavaScript. Калі ласка, актывуйце JavaScript у вашым браўзеры.'
![Selection_017](https://user-images.githubusercontent.com/53947213/63158887-eaaae480-c022-11e9-81f6-31f5da881255.png)

b. Change url in address bar to incorrect and press Enter

**Result:** Page with 'Cannot GET <url>' messages appears.
**Expected:** need to be discussed... May be, messages that this page is not exist and button that allows user to go to the landing page?
![Selection_018](https://user-images.githubusercontent.com/53947213/63159730-dd8ef500-c024-11e9-8fb6-63d8ac98b918.png)

**Comment by dmitrap** [comment]
fix'd

**Comment by rizomaa** [comment]
@dmitrap where is the pull request for the issue?
