### ISSUE TITLE
[3.6] Initiatives(events also can be affected) details - image is not shown

### ISSUE THREAD

**Issue by antos-k** [diglabby/mapa#163]
1. Open map
2. Press 'Add new entry' (or edit existing event)
3. Select 'Initiative' category
4. Fill all fields correctly
5. Fill Image field correctly - for example https://pp.userapi.com/c857736/v857736486/4458a/xmgrrpcq_Ek.jpg
6.  press Save

**Results:** Image is not shown at initiative details. 
Notice: the same image is shown correctly at https://kartevonmorgen.org/#/?entry=e10f6cff81ca415089858a035044ff06&zoom=9.00
Notice2: events also can be affected - can't check it now before blocker will be fixed

**Expected:** Image is shown

![No image shown](https://user-images.githubusercontent.com/53947213/63183157-fe733c80-c05c-11e9-99ae-a94c3e8e3c95.png)

**Comment by rizomaa** [comment]
@Anthony-Hoopkins could you make full description of the task?

**Comment by wellemut** [comment]
Dear @antos-k 
In my browser, the immage of this entry is perfectly showing: https://mapa.falanster.by/#/?entry=e10f6cff81ca415089858a035044ff06&zoom=15.00

If you have problems that the immage is not loading, it seems to be a local problem in your browser. 
Thats why I close this issue, untill someone els will report this problem.

**Comment by rizomaa** [comment]
have the same

**Comment by PolinaSam** [comment]
everything works. bug fixed
