### ISSUE TITLE
[5][8] add wrapper for button and modal

### ISSUE THREAD

**Issue by JustOneJance** [diglabby/mapa#164]
- add wrapper for button and modal window
- create action to add iframe in redux
- create reducer for iframe
- connect wrapper to redux
-connect mainViewModal to redux

**Comment by rizomaa** [comment]
@JustOneJance where is the pull request for the feature

@tragladit  would like to know more how you implement this.

**Comment by rizomaa** [comment]
@fr0zen did you ave any PR relating the issue?

**Comment by rizomaa** [comment]
@fr0zen how to make visual test here?
