### ISSUE TITLE
[NN] Too big font in a description and title fields

### ISSUE THREAD

**Issue by rizomaa** [diglabby/mapa#166]
![Selection_040](https://user-images.githubusercontent.com/9870374/63192769-8f094700-c074-11e9-964e-c3128b51492a.png)

**Comment by rizomaa** [comment]
1. Left alignment
2. Font size title
3. Font size description
@dmitrap 
![Selection_042](https://user-images.githubusercontent.com/9870374/63208356-93b51600-c0db-11e9-9e09-15cca41ff2b9.png)

**Comment by dmitrap** [comment]
fix'd
