### ISSUE TITLE
[Design] Favicon

### ISSUE THREAD

**Issue by svetit** [diglabby/mapa#171]
Add favicon to landing

**Comment by svetit** [comment]
![Uploading mapa_favicon.png…]()

**Comment by svetit** [comment]
![mapa_favicon](https://user-images.githubusercontent.com/1722996/63209519-9703ce00-c0ea-11e9-9709-85584340c94f.png)

**Comment by rizomaa** [comment]
@svetit you duplicated other task created earlier 
https://github.com/diglabby/mapa/issues/160

**Comment by svetit** [comment]
![mapa_favicon](https://user-images.githubusercontent.com/1722996/70263185-cf690e00-17a6-11ea-8527-bd84f958bb7a.png)

**Comment by rizomaa** [comment]
Could i share the task for a developer? @svetit

**Comment by svetit** [comment]
@rizomaa  Sure! I am waiting for new favicon:)

**Comment by rizomaa** [comment]
as far as I see, now, it is ok. close the issue @svetit
