### ISSUE TITLE
[NN] Change a place for a login link

### ISSUE THREAD

**Issue by rizomaa** [diglabby/mapa#177]
![Selection_044](https://user-images.githubusercontent.com/9870374/63211067-0bdf0400-c0fb-11e9-808d-88980e94cf4f.png)
![Selection_043](https://user-images.githubusercontent.com/9870374/63211068-0c779a80-c0fb-11e9-8609-e62c9b01b7c3.png)

**Comment by fr0zen** [comment]
@rizomaa login link is hidden now

**Comment by PolinaSam** [comment]
@fr0zen @rizomaa, what is the current status of this task?

**Comment by rizomaa** [comment]
Login totally disappered... so we need to move the link to the bottom part

**Comment by k-gorod** [comment]
I think our main goal is to do tool for people(means mapa). In today reality people counting every second, and thats why our objective is to make mapa as practical as possible. First reason why people can visit this site is to find or to creat some event, and that why this buttons(login, map, find event) must be first, what they(users) will see. Thats why I suggest to move on the bottom of page links, what usual user dont want to see first(partners, donations, contacts, team),coz user must read and know minimal information to do his main goal. It will makes intuitively understanding user interface. And i suggest to do main buttons(links) more noticeable. 

imho.

What you think?

**Comment by rizomaa** [comment]
@k-gorod Sounds reasonable. Here we discuss only the login link shifting.

Further steps:
1. Please complete the initial task.
2. And move your idea to a new separate issue to discuss all the detail with designer @foksia07 before, and after we can move it for implementation.

**Comment by k-gorod** [comment]
PR created 
![image](https://user-images.githubusercontent.com/58625453/83254244-25979680-a1b7-11ea-9032-ef324e1b73bd.png)

**Comment by rizomaa** [comment]
@k-gorod cool! merged
