### ISSUE TITLE
is:issue is:open [NN] meta image is still "Karte Von Morgen"

### ISSUE THREAD

**Issue by dmitrap** [diglabby/mapa#187]

**Comment by dmitrap** [comment]
should be mapa logo probably?

**Comment by rizomaa** [comment]
@dmitrap yes, where would you like to add the logo?

@svetit

**Comment by PolinaSam** [comment]
@dmitrap, you talking about the logo in the header?

**Comment by rizomaa** [comment]
@PolinaSam here is the topic about open graph for social networks,
For example, you put mapa link to the some social network and it starts parsing the link and retrieve picture. 
What a default picture will be? 
That is the essense of the task. Now it needs to be tested.

**Comment by k-gorod** [comment]
It is already implemented.
In code (src/index.html):
![image](https://user-images.githubusercontent.com/58625453/83205486-5a740100-a157-11ea-8719-79ceb7c37958.png)

It is looking like that on Facebook now:
![image](https://user-images.githubusercontent.com/58625453/83204650-02d49600-a155-11ea-8085-1a32276b7840.png)
Like that in VK:
![image](https://user-images.githubusercontent.com/58625453/83204892-a7ef6e80-a155-11ea-9803-ef252ec2b0ae.png)
To vk will show picture, we can try  add this line:
`<meta property="vk:image"  content="https://wiki.falanster.info/w/images/a/ad/Mapa_logo_9.png" />`
At least it is advised by vk's documentation.
And i can add description you want. It is empty now.
But the main idea of this issue already was realized.

**Comment by rizomaa** [comment]
@k-gorod thank you for testing the case I will move to the done column
