### ISSUE TITLE
Make inactive the Events button 

### ISSUE THREAD

**Issue by rizomaa** [diglabby/mapa#188]
![Selection_001](https://user-images.githubusercontent.com/9870374/64101160-e4806c00-cd75-11e9-94a8-a944a9db01ef.png)

**Comment by rizomaa** [comment]
here is until we complete the feature fully and without bug

**Comment by Anthony-Hoopkins** [comment]
@rizomaa  @fr0zen https://github.com/diglabby/mapa/pull/190
