### ISSUE TITLE
Create list of libraries, that we can use for mail sending via subscriptions.

### ISSUE THREAD

**Issue by fr0zen** [diglabby/mapa#19]
- [x]  Write list of libraries
- [ ]  Write pros and cons of every library
- [ ]  Decide, what library is better for subscription functionality  #6

**Comment by ksandrsis** [comment]
1)  [https://github.com/nodemailer/nodemailer/](url)
2)  [https://github.com/niftylettuce/email-templates](url)
3) [https://github.com/eleith/emailjs](url)
4)  [https://github.com/eladnava/mailgen](url)

Stats https://pp.userapi.com/c850128/v850128040/18a400/wu7E4Rqp0r0.jpg

Basically, I’m going to work, but Nodemailer has more functions and better documentation.
[https://github.com/nodemailer/nodemailer/](url)


If only I understood you correctly and you asked to find libraries for sending mail, and not libraries for working with Api services for sending mail

**Comment by rizomaa** [comment]
@ksandrsis could you please to add more information around email-templates, emailjs, mailgen relating to potential implementation in Mapa
1/ Updatability
2/ Easy to install
3/ Community of developers
4/ Protocols supports
Thanks
Mikhail

**Comment by ksandrsis** [comment]
1 https://github.com/niftylettuce/email-templates

Used only for creating templates.
There is support for CSS, images, fonts.
There is a preview template.
Poisoning is done with the help of Nodemailer
Last updated June 2019.
Actively maintained and updated by developers.
Easy to install.
Supports Nodemailer protocols: SSL and TLS.

2 https://github.com/eladnava/mailgen


Used only for creating templates.
There is support for several pre-installed themes.
You can save the template to a local file - to get a template from a file (or the text of the letter).
RTL supports.
Gmail GotoActions.
Poisoning is done with the help of Nodemailer
Last updated January 2019.
Actively maintained and updated by developers.
Easy to install.
Supports Nodemailer protocols: SSL and TLS.

3 https://github.com/eleith/emailjs

Used to create templates and SEND letters.
Last updated November 2018.
Easy to install (I tried to run - lines of code!).
Supports SSL and TLS protocols.
https://pp.userapi.com/c850136/v850136037/18fd1f/5P-HoBZ9ykU.jpg

**Comment by rizomaa** [comment]
@ksandrsis thanks for the research. Now, we will analyse these results. 

Now we can switch to a new task.

**Comment by rizomaa** [comment]
@fr0zen I close the issue.
