### ISSUE TITLE
[4][NN]To hide subscription feature from UI

### ISSUE THREAD

**Issue by rizomaa** [diglabby/mapa#192]

**Comment by rizomaa** [comment]
![Selection_003](https://user-images.githubusercontent.com/9870374/64549073-9dc3e080-d338-11e9-8e76-7e2d1435b18f.png)

**Comment by rizomaa** [comment]
@fr0zen is this feature is bad or good implemented?

**Comment by rizomaa** [comment]
@fr0zen what do you want we test here?

**Comment by PolinaSam** [comment]
all changes accepted. the issue can be deployed
