### ISSUE TITLE
Change the logo on the top right corner from KVM to Mapa

### ISSUE THREAD

**Issue by rizomaa** [diglabby/mapa#196]
![Selection_048](https://user-images.githubusercontent.com/9870374/64720151-6ee17200-d4d2-11e9-8348-629a6c06e763.png)

**Comment by tragladit** [comment]
it's all right? 
![logo_issue](https://user-images.githubusercontent.com/35130345/64724067-61c88100-d4da-11e9-9803-44cfeb6151a6.png)

**Comment by svetit** [comment]
![mapa_m](https://user-images.githubusercontent.com/1722996/64728837-95a8a400-d4e4-11e9-82e7-4a693b9c0588.png)

**Comment by svetit** [comment]
@tragladit Please, use my image

**Comment by tragladit** [comment]
? 
![logo_issue](https://user-images.githubusercontent.com/35130345/64729662-41062880-d4e6-11e9-824a-0eae72a85d9d.png)

**Comment by svetit** [comment]
@tragladit excellent! :)

**Comment by rizomaa** [comment]
@tragladit could you close the task when it is moved to production server. Because now we have now the funxction on the production server.

@fr0zen any updates here around deployment on production server?

**Comment by PolinaSam** [comment]
no bag. can be deployed
