### ISSUE TITLE
Put the logo of our info partners on the web-site mapa.falanster.by

### ISSUE THREAD

**Issue by svajamajka** [diglabby/mapa#198]
Here is a folder with logo: https://drive.google.com/file/d/0B_iPujzwhOxvZmlrVGEwV3pEdWtQalEtTDNhc3JqM0twMFAw/view?usp=sharing

**Comment by PolinaSam** [comment]
@svajamajka i'm not able to download this file from Google Drive to check the logo is to add. please, can you send this doc one more time?

**Comment by rizomaa** [comment]
Many new logos were added new pack will be in new issue.

@fr0zen many thanks
