### ISSUE TITLE
Create link to switch to belarussian translation on mapa.

### ISSUE THREAD

**Issue by fr0zen** [diglabby/mapa#20]
Place link in one line with other existing languages. After clicking the link interface must change accordingly localization file on belarussian. #5 

- [ ]  Create a link in template.
- [ ]  Link must switch interface to belarussian language
- [ ]  Translate must be taken from localization file.

**Comment by wellemut** [comment]
Do you mean the normal language switch at the upper right corner?

**Comment by rizomaa** [comment]
> Do you mean the normal language switch at the upper right corner?

@wellemut yes, you are correct

**Comment by rizomaa** [comment]
@ihargit hello,
Do you have any questions around the issue?

**Comment by rizomaa** [comment]
@antos-k is this ready already?
