### ISSUE TITLE
make a clickable heading inside a profile

### ISSUE THREAD

**Issue by anna-tolchikova** [diglabby/mapa#201]
for better and expected UX would be great to make clickable a headline in an initiative profile:
<img width="352" alt="Снимок экрана 2019-09-15 в 0 39 04" src="https://user-images.githubusercontent.com/7893260/64913968-7f078480-d752-11e9-9642-607ff6f4aabb.png">

**Comment by rizomaa** [comment]
@anna-tolchikova could you explain you idea in details, because not it is clickable
