### ISSUE TITLE
To change notification for adding tags (push enter after each tag)

### ISSUE THREAD

**Issue by rizomaa** [diglabby/mapa#213]
1. Should it be only Enter!
2. Comma?

**Comment by wellemut** [comment]
You allway just need to push enter to use the first suggestions.

My need would be, that the coursers stay in the tag field, after you have chosen an tag, so that you can use it right on. That is extremly helpful on smartphone. (At the moment, the keyboard closes after each selections of a tag.)

**Comment by rizomaa** [comment]
@wellemut thanks for the comment 
close. 
the task is doubled.
