### ISSUE TITLE
[NT1] Create Postcards about "Mapa" to send civic initiatives.[Designer + Communicator]

### ISSUE THREAD

**Issue by svetit** [diglabby/mapa#22]
**Designer:**
Create a design of a two side postcard (under CC BY-SA license). Share the original file, file in .jpg .
For print. A6.
One side: picture about Mapa, message, link mapa.falanster.by
Another side: message, qr code to mapa.falanster.by , link mapa.falanster.by, instruction how add the organization and what for.

Mapa Brandbook: https://wiki.falanster.info/wiki/Брэнд_Мапы_заўтрашняга_дня

**Communicator:**
1/ Create text in belarusian language for both sides of a postcard.
2/ Create a database of belarusian initiatives. (With columns:Title, City, Address (official address for post), Name of leaders)

**Comment by rizomaa** [comment]
@svetit you can create here check list like in trello. Please you the rightest button the the list block panel
