### ISSUE TITLE
UI bug with description field

### ISSUE THREAD

**Issue by Dissfall** [diglabby/mapa#227]
Due to the fact that the input field description has the ability to change the horizontal size. Resizing can lead to a strange result (I think by the fact that changing the size of the field affects the size of the parent block, on which the sizes of other fields depend). I propose to make the horizontal size fixed or fix all sizes with the ability to scroll

![bug](https://user-images.githubusercontent.com/28986337/66516241-448ece80-eae9-11e9-9bb1-f0f8b53a5a4b.png)

**Comment by rizomaa** [comment]
@Dissfall what environment (browser version, OS) did you use?

**Comment by rizomaa** [comment]
@Anthony-Hoopkins can you see such a bug?

**Comment by Dissfall** [comment]
Hi, @rizomaa My browser is Firefox 68.0 and OS is Arch Linux
