### ISSUE TITLE
[NT3] Create a message phrase for target groups: volunteers, civic organizations. [PR, communicator]

### ISSUE THREAD

**Issue by svetit** [diglabby/mapa#24]
Create three messages:
1/ for volunteers. (People, who will help to add points on mapa)
2/ for civic organizations.
3/ for users. (People, who will want to find and join some organizations)

**For that you need to understand the deep goal of Mapa project:** 
The Mapa will help the initiatives to find each other easily. That means to build partnership, to implement more good project for society development. More horizontal connections in the society.
More people will have the opportunity to observe the actions of civic organizations, they will become more visualized for common people, non activists.
With Mapa more people will have the opportunity to find organizations on topics that they interested in, want to help and then to join this organizations.

**Comment by rizomaa** [comment]
@svetit do you think it will sound with similar effect in different languages? How did you conside multilingual factor here?
