### ISSUE TITLE
To change text in tag field and websites field

### ISSUE THREAD

**Issue by rizomaa** [diglabby/mapa#247]
- [ ] Instead of "Тэгі (праз коску)" put "Тэгі (праз энтэр)"
- [ ] In field Website change from "Галоўная" to "Сайт/паблік"

**Comment by blinkoliver** [comment]
Sorry but don't understand. Please clarify. Just need to change the tags in the JSON file trnslation-by?

**Comment by rizomaa** [comment]
@blinkoliver please have a look on the screenshot. Here is the fields where we need to change text. Does it make sense?

About solution. This is your choice=)
![Selection_005](https://user-images.githubusercontent.com/9870374/72896115-08961700-3d30-11ea-9f29-33faf0f2b41b.png)
