### ISSUE TITLE
[NT4] Create a blogpost and a slide: how to use Mapa as a iframe map on contacts page of a website. [Journalist + Designer]

### ISSUE THREAD

**Issue by svetit** [diglabby/mapa#25]
**Journalist, writer:**
1/ Discover how to use Mapa as a iframe map on contacts page of a website. (Ask people from KVM)
2/ Write a text about how to use Mapa as a iframe map on contacts page of a website.
In google doc. Share everyone access by the link. Add screenshots.

**Designer:**
1/ Create a slide for PoverPoint presentation about Mapa.
Title of slide: use Mapa as a iframe map on contacts page of a website
Add screenshot.
(For the screenshot the designer need to discover the topic).

**Comment by rizomaa** [comment]
Related but tech issue https://github.com/diglabby/mapa/issues/7
