### ISSUE TITLE
What is Civic-Tech in Germany

### ISSUE THREAD

**Issue by eeeennoooo** [diglabby/mapa#29]
A short presentation of Helmut to present Civic-Tech in Germany

**Comment by rizomaa** [comment]
Sounds interestings

@wellemut did you discuss the moment yesterday?

**Comment by wellemut** [comment]
We did not discuss it yet. I could summurize a bit, which we discussed at the wechange Workshop in Berlin, https://bildungsagenten.org/civictech/ but in the open source will be most of it.
civic tech is just the question, how we finance open source.
