### ISSUE TITLE
Усталёўка Мапы. Што робім з докерам?

### ISSUE THREAD

**Issue by lavana555** [diglabby/mapa#290]
я развернул проект(mapa) все ок работает
у меня вопрос был в том что делать с docker(его инсталить?)

**Comment by rizomaa** [comment]
> я развернул проект(mapa) все ок работает
> у меня вопрос был в том что делать с docker(его инсталить?)

@lavana555 пакуль ставім усё натыўна. докер пакідаем на пасля.
Скінь калі ласка пару скрыной як ўсё выглядае. Будзем далей рухацца.

**Comment by lavana555** [comment]
![image](https://user-images.githubusercontent.com/57916126/77332041-92636000-6d32-11ea-91ff-49a713681709.png)

**Comment by lavana555** [comment]
![image](https://user-images.githubusercontent.com/57916126/77332086-a27b3f80-6d32-11ea-9cc4-b7e8f19a7eac.png)

**Comment by lavana555** [comment]
так должно быть?

**Comment by rizomaa** [comment]
@lavana555 маеце на ўвазе канфіг ці лог білда?

**Comment by lavana555** [comment]
да хотелось бы знать что дальше делать после этого
