### ISSUE TITLE
[Content] Define what content need to be added to landing

### ISSUE THREAD

**Issue by svetit** [diglabby/mapa#30]
Here is the content for the landing https://docs.google.com/document/d/1PuRKaEZwTPCVM3MPTf5fkaN0Y_dr3wBqG0RVAMWk56A/edit#heading=h.2f7vqb6u20my

**Comment by rizomaa** [comment]
@svetit what do you want i do here?

**Comment by rizomaa** [comment]
@svetit one more time...  any thing you need here?

**Comment by svetit** [comment]
@rizomaa I did not needed you help here.
