### ISSUE TITLE
Can`t install project

### ISSUE THREAD

**Issue by Hmekus** [diglabby/mapa#310]
I cloned the project, in the root folder did **npm install** then changed src/constants/URLs.js to[https://github.com/goodmap/goodmap-old/blob/e9658f1d2a8d77effe4cfabc085b5c7a2c65c3f3/src/constants/URLs.js#L64](url)  and add **link: window.location.protocol + "//" + "api.ofdb.io/v0"**, in OFDB_API. When i entered **npm start**, i get working project, but page in my browser was blank.

![Screenshot from 2020-04-08 16-48-41](https://user-images.githubusercontent.com/56358268/78791738-ef107d00-79b8-11ea-969f-b4966e46a267.png)
I tried install local OpenFairDB, download archive from releases in src/constants/URLs.js changed OFDB_API to **link: window.location.origin + "/api" //use when you run openfairdb locally**, launched it, then turn off, changed the databases to those in the readme, turn on again. Then entered npm start in root folder of the mapa and get the same blank page. What am i doing wrong?

**Comment by rizomaa** [comment]
@Hmekus please add here what is your browser console shows.

**Comment by rizomaa** [comment]
@Hmekus try the guide also https://github.com/diglabby/mapa/wiki/Installation-guide-(by-rizomaa)

**Comment by Hmekus** [comment]
> @Hmekus try the guide also https://github.com/diglabby/mapa/wiki/Installation-guide-(by-rizomaa)

I tried this one, and get an error after entered npm start
![Screenshot from 2020-04-18 19-09-54](https://user-images.githubusercontent.com/56358268/79642900-b6d32080-81a8-11ea-94d5-d5a29060b7ba.png)

**Comment by rizomaa** [comment]
@Hmekus 

першы белы экран і праблема тут розныя.
падазраю, што не усё скапіравалася. 

зы
звяжу вас з @lavana555 магчыма вы разам зможаце ўсталяваць.

**Comment by lavana555** [comment]
you don't need to install openfairdb here, just replace the object as specified in the readme. Use yarn instead of npm. Then as in the IDE it will be compiled successfully Open it in your browser https://localhost:8080. If there is nothing open the console and what are the errors there

**Comment by lavana555** [comment]
@Hmekus you don't need to install openfairdb here, just replace the object as specified in the readme. Use yarn instead of npm. Then as in the IDE it will be compiled successfully Open it in your browser https://localhost:8080. If there is nothing open the console and what are the errors there

**Comment by Hmekus** [comment]
@lavana555  first of all, in both guides requirements says use node 6.x . When i tried use yarn i get a node version error
![Screenshot from 2020-04-19 13-13-54](https://user-images.githubusercontent.com/56358268/79685827-4974cd80-8244-11ea-9df4-754711f50487.png)
then it failed. I switched node to 8.x, run and get blank page, below u can see the console
![Screenshot from 2020-04-19 13-42-07](https://user-images.githubusercontent.com/56358268/79685872-9fe20c00-8244-11ea-8e3c-cf50850b5b10.png)
 Then i did same actions with @rizomaa s guide and mapa has earned!! I should use yarn instead of npm. It strange cause i used yarn during the first installation
![Screenshot from 2020-04-19 14-15-21](https://user-images.githubusercontent.com/56358268/79686332-44b21880-8248-11ea-9679-4e8937779ef7.png)
