### ISSUE TITLE
[Design] Select images of people from team

### ISSUE THREAD

**Issue by svetit** [diglabby/mapa#32]
Collect square images of people from team

**Comment by rizomaa** [comment]
Do you mean @Nika987 @fr0zen yours and mine?

**Comment by svetit** [comment]
@rizomaa  sure.
 Now I think about just me you Frozen

**Comment by svetit** [comment]
![rizoma_mapa_2](https://user-images.githubusercontent.com/1722996/62454231-a004af00-b77c-11e9-83c9-97b970fa6d34.jpg)
rizoma

**Comment by svetit** [comment]
![frozen_mapa](https://user-images.githubusercontent.com/1722996/62454257-a85cea00-b77c-11e9-911e-b43f7a5d044c.jpg)
frozen

**Comment by svetit** [comment]
![svet_mapa](https://user-images.githubusercontent.com/1722996/62454272-af83f800-b77c-11e9-9e4e-7db5a91b17b2.jpg)
me

**Comment by svetit** [comment]
@fr0zen  here are photos. Can you make them round with react?

**Comment by fr0zen** [comment]
@svetit yes, sure, i will round images with css, thanks
