### ISSUE TITLE
Стажер. Установка базы.

### ISSUE THREAD

**Issue by k-gorod** [diglabby/mapa#341]
![image](https://user-images.githubusercontent.com/58625453/81958678-ff022900-9616-11ea-85dc-40c09aca4c26.png)
Да, я попробовал сделать так как написано для удаленной базы. 
![image](https://user-images.githubusercontent.com/58625453/81959196-c4e55700-9617-11ea-9618-30dd0da059e2.png)
![image](https://user-images.githubusercontent.com/58625453/81962059-e1838e00-961b-11ea-94f6-63f9841900e3.png)

В интернете ответы на эту тему скорее локальные. Но все же я попробовал:npm i cross-env --save  ,   и на всякий случай попробовал npm install --save-dev cross-env.

А ссылка на готовый пак в инструкции тоже битая. Мне без разницы локально будет у меня стоять база или нет, поэтому прошу помочь с наиболее рабочим вариантом. 

Как я и сказал я никогда не занимался подобными вещами, и мне нужна помощь.

**Comment by k-gorod** [comment]
Ну и судя по вопросам, я не один такой, у кого проблемы с этой базой.

**Comment by rizomaa** [comment]
@k-gorod дзякуй апісанне гэтаі ішус.

Якія у вас версіі 
nodejs
npm
ці карыстаецеся віртуальнымі машынамі?

**Comment by k-gorod** [comment]
![image](https://user-images.githubusercontent.com/58625453/81965373-a33c9d80-9620-11ea-92cd-be7fd7a43f54.png)
Нет не пользуюсь виртуальными машинами, если я правильно понял вопрос. Просто мой компьютер.

**Comment by rizomaa** [comment]
@k-gorod  Можна цлкам лог, на які спасылаецца паведамленне пра памылку?

**Comment by k-gorod** [comment]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'Z:\\Progrms\\Node\\node.exe',
1 verbose cli   'Z:\\Progrms\\Node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle kartevonmorgen@0.1.30~prestart: kartevonmorgen@0.1.30
6 info lifecycle kartevonmorgen@0.1.30~start: kartevonmorgen@0.1.30
7 verbose lifecycle kartevonmorgen@0.1.30~start: unsafe-perm in lifecycle true
8 verbose lifecycle kartevonmorgen@0.1.30~start: PATH: Z:\Progrms\Node\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;Z:\Code\Falan\mapa\node_modules\.bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;Z:\Progrms\Git\cmd;Z:\Progrms\Node\;C:\Users\coolk\AppData\Local\Microsoft\WindowsApps;Z:\Progrms\Microsoft VS Code\bin;C:\Users\coolk\AppData\Roaming\npm
9 verbose lifecycle kartevonmorgen@0.1.30~start: CWD: Z:\Code\Falan\mapa
10 silly lifecycle kartevonmorgen@0.1.30~start: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'cross-env NODE_ENV=development webpack-dev-server --progress --host 0.0.0.0 --hot --https'
10 silly lifecycle ]
11 silly lifecycle kartevonmorgen@0.1.30~start: Returned: code: 1  signal: null
12 info lifecycle kartevonmorgen@0.1.30~start: Failed to exec start script
13 verbose stack Error: kartevonmorgen@0.1.30 start: `cross-env NODE_ENV=development webpack-dev-server --progress --host 0.0.0.0 --hot --https`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (Z:\Progrms\Node\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (Z:\Progrms\Node\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid kartevonmorgen@0.1.30
15 verbose cwd Z:\Code\Falan\mapa
16 verbose Windows_NT 10.0.18362
17 verbose argv "Z:\\Progrms\\Node\\node.exe" "Z:\\Progrms\\Node\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.16.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error kartevonmorgen@0.1.30 start: `cross-env NODE_ENV=development webpack-dev-server --progress --host 0.0.0.0 --hot --https`
22 error Exit status 1
23 error Failed at the kartevonmorgen@0.1.30 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by k-gorod** [comment]
Попробовал npm install, на всякий случай. Не помогло

**Comment by rizomaa** [comment]
@k-gorod
Вось тут ад іншага ўдзельніка прыйшла інфа 

> Змог запусціць пасля замены радка
> "start": "cross-env NODE_ENV=development webpack-dev-server --progress --host 0.0.0.0 --hot --https"
> на 
> "start": "webpack-dev-server --mode development --watch".
> Усё працуе).

Паспрабуйце,

калі не пойдзе я папрашу яго далучыцца.

**Comment by k-gorod** [comment]
![image](https://user-images.githubusercontent.com/58625453/82062947-8a40f480-96d3-11ea-8035-6294bb2bc361.png)

**Comment by k-gorod** [comment]
Ну тут дело получается либо в конфигах раз он прям на старте ругается. Либо у меня что-то не софта не установлено, либо установлено не правильно. Ну т.е. дело не в бд вообще.
Получается вопрос может быть даже в чем-то ну вообще очевидном и само собой разумеющемся, мне бы побольше вариантов накинуть, я бы все проверил. Потому что я это не нагуглю. Тут нужно понимать что откуда берется и куда девается.

**Comment by rizomaa** [comment]
@k-gorod 
Пакуль думкі такія
1. Паставіць віртуалку (туды ubuntu, mint) і паспрабаваць запусціць з яе увесь асяродак. 
2. mapa гэта ў вас карнявая тэчка?
3. пакажыце, што ў вас у канфіге url.js

**Comment by k-gorod** [comment]
1)Т.е. проект невозможно запустить без виртуальной машины? Что? И мне нужно разбираться с виртуальными машинами и уж тем более на другой ОС, когда проект багается на первой строчке(start)?
2)Ну конечно. Я же клоню проект из гитхаба. И в Вашем проекте корень-это mapa.

**Comment by k-gorod** [comment]
3)конфига URL не нашел. Если только сам файл с константами. Но я так понял это не он, потому что до него программа и не доходит, так как ломается на строчке start
import { APP_STAGES } from "./App"

// for Internet Explorer:
if (!window.location.origin) {
  window.location.origin = window.location.protocol + "//" + window.location.hostname + (window.location.port ? ':' + window.location.port: '');
}

const API_VERSION = 'v0';

const OFDB_API_LINK = (() => {
  switch (__STAGE__){
    case APP_STAGES.LOCAL:

      console.log('env LOCAL');

      return "https://dev.ofdb.io/";
      // return "https://kartevonmorgen.org/api/";
      // return "https://api.ofdb.io/";
      // return "https://nightly.ofdb.io/";

    case APP_STAGES.NIGHTLY:
      console.log('env NIGHTLY');
      return "https://nightly.ofdb.io/";

    case APP_STAGES.DEV:
      console.log('env DEV');
      return "https://dev.ofdb.io/";

    default:
      // production  // ?? api.ofdb.io ??
      return "https://kartevonmorgen.org/api/";
  }
})() + API_VERSION;

module.exports = {
  CC_LICENSE: {
    by: {
      name: "creativecommons.org/publicdomain/zero/1.0/deed.be",
      link: "https://creativecommons.org/publicdomain/zero/1.0/deed.be"
    },
    en: {
      name: "creativecommons.org/publicdomain/zero/1.0/deed.en",
      link: "https://creativecommons.org/publicdomain/zero/1.0/deed.en"
    }
  },
  ODBL_LICENSE: {
    name: "opendatacommons.org/licenses/odbl/summary/",
    link: "https://opendatacommons.org/licenses/odbl/summary/"
  },
  APP: {
    name: "kartevonmorgen.org",
    link: "https://kartevonmorgen.org"
  },
  PROTOTYPE: {
    name: "prototyp.kartevonmorgen.org",
    link: "https://prototyp.kartevonmorgen.org"
  },
  REPOSITORY: {
    name: "https://github.com/diglabby/mapa",
    link: "https://github.com/diglabby/mapa"
  },
  VK: {
    name: "https://vk.com/falanster_by",
    link: "https://vk.com/falanster_by"
  },
  TELEGRAM: {
    name: "https://t.me/hackmapagithub",
    link: "https://t.me/hackmapagithub"
  },
  FACEBOOK: {
    name: "facebook.com/falanster",
    link: "https://www.facebook.com/falanster.by"
  },
  MAIL: {
    name: "falanster.by@gmail.com",
    link: "mailto:falanster.by@gmail.com"
  },
  OSM_ATTR: {
    name: "OpenStreetMap",
    link: "https://osm.org/copyright"
  },
  TILE_SERVER: {
    link: "https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}{r}.png"
  },
  TILE_SERVER_ATTR: {
    name: "Wikimedia",
    link: "https://wikimediafoundation.org/wiki/Maps_Terms_of_Use"
  },
  OFDB_API: {
    link: window.location.protocol + "//" + "api.ofdb.io/v0" 
  },
  TH_GEOCODER: {
    link: "https://geocoder.tilehosting.com/q/<query>.js?key=<key>"
  },
  NOMINATIM: {
    link: "https://nominatim.openstreetmap.org"
  },
  ROUTEPLANNERS: {
    default: {
      name: "Graphhopper Maps",
      link: "https://graphhopper.com/maps/?point=&point={addr}&locale=de-DE&vehicle=bike&weighting=fastest&elevation=false&use_miles=false&layer=Omniscale"
    },
    apple: {
      name: "Apple Maps",
      link: "http://maps.apple.com/?daddr={addr}&dirflg=w"
    },
    android: {
      name: "GeoURI",
      link: "geo:{lat},{lng}"
    }
  },
  DONATE: {
    name: "www.betterplace.org/de/projects/36213",
    link: "https://www.betterplace.org/de/projects/36213"
  },
  JOB_ADS: {
    name: "www.betterplace.org/de/organisations/vonmorgen",
    link: "https://www.betterplace.org/de/organisations/vonmorgen"
  }
};

**Comment by k-gorod** [comment]
В этом проекте участвует хоть один человек поставивший его на Виндоус?

**Comment by rizomaa** [comment]
@k-gorod 
працуем у асяродку linux.

1. праект стаіць у дзясткаў чалавек (ставілі па гайду ў тым ліку на віндзе). дапускаю, што ў  канфігах для npm ці node ёсць пытанні. таму каб не капаць нераскопваемае, 
1.1. віртуалка можа дапамагчы. 
1.2*. наогул раім, калі вы плануеце сур'ёзна звязаць сябе з вэб-распрацоўкай, карыстацца *unix сістэмамі.

Што са свайго боку магу яшчэ зрабіць:
1. Запрашу ўдзельніка які справіўся з падобнай задачай, каб ён падзяліўся сваім досведам,  магчыма вам гэта дапаможа.
2. Таксама праз тыдзень зладзіць вэбінар з дэманрацыяй усталёўкі праекта (так, на лінукс) як на лакальную базу так і дыстанцыйна.

Файл гэты павінен быць: src/constants/URLs.js
Зараз у корні ляжыць яго базавы ўзор.

**Comment by ArtyomKr** [comment]
Привет, а ты пробовал использовать yarn вместо npm? Вроде у кого-то тоже была проблема с запуском и использование yarn помогло.

**Comment by chizhovm** [comment]
Привет всем! У меня машина на Windows. Решение мое. При изменении строки
 "start": "cross-env NODE_ENV=development webpack-dev-server --progress --host 0.0.0.0 --hot --https"
на
"start": "webpack-dev-server --mode development --watch".
проект запускается на http://localhost:8080/
После чего все исправно работает.
1) git clone <link>;
2) npm i;
3) Меняем строчку;
4) npm start.

**Comment by k-gorod** [comment]
Итак да, запустил. 2 последних комментария очень помогли. 
Я попробовал yarn,  мой терминал начал выдавать совершенную несуразицу. Поэтому я запустил дефолтный терминал cmd windows ,  уже увидел признаки жизни как с ярн, так и с нпм. 
Потом заменил строчку start, о которой упоминают не впервой и проект запустился. 
Проблема заключалась в powershell(который был предустановлен в мое VSCode и шел по дефолту) и в строчке start.
Всем большое спасибо. Жду заданий.

**Comment by rizomaa** [comment]
@k-gorod віншуем вас=)

@ArtyomKr @chizhovm дзякуй за дапамогу і ўдзел
