### ISSUE TITLE
Install KVM instance with a local database

### ISSUE THREAD

**Issue by rizomaa** [diglabby/mapa#35]
there are several related tasks:
1. https://github.com/goodmap/goodmap-old/issues/581
2. https://github.com/goodmap/goodmap-old/pull/583

**Comment by KonstantinKudelko** [comment]
![image](https://user-images.githubusercontent.com/16194085/61775377-86b94580-ae01-11e9-8f31-b5f62c2c5147.png)

I have troubles with `npm install` every time this process stops. (See screenshot)

**Comment by KonstantinKudelko** [comment]
Resolved this by using `yarn`

**Comment by rizomaa** [comment]
@fr0zen please join the process. 

@KonstantinKudelko on what step are you?

**Comment by KonstantinKudelko** [comment]
@rizomaa I can't run the DB.

`-bash: ./openfairdb: cannot execute binary file`
Mac OS

**Comment by rizomaa** [comment]
@KonstantinKudelko please ask @uklotzde from the issue https://github.com/goodmap/goodmap-old/issues/581 directly. You can continue the issue there until Uwe join us here. I've sent him invitation.

**Comment by fr0zen** [comment]
@KonstantinKudelko As i know, it's impossible to run linux binaries on MacOS without some kind of virtualization or third-party tools. It means that you need to run some linux virtual mashine on your host, and execute binary inside this VM. For now we are looking how to simplify all this process of installation.

**Comment by uklotzde** [comment]
Build from source, Docker, ... no need for a VM.
