### ISSUE TITLE
[Developer] Create new landing structure

### ISSUE THREAD

**Issue by fr0zen** [diglabby/mapa#38]
[Developer] Explore whole landing structure https://github.com/diglabby/mapa/blob/master/src/components/LandingPage.jsx 
https://github.com/diglabby/mapa/tree/master/src/components/pure and make structural changes according to designs. Design available at https://www.figma.com/file/XLHeFtj7qOv0G3J8Eh1EeYWK/Mapa?node-id=0%3A1

**Comment by fr0zen** [comment]
Sections that need to be implemented:

- [ ] Top menu
- [ ] Mapa applications from KVM
- [ ] Аbout us section
- [ ] Goals
- [ ] For who
- [ ] Principles
- [ ] How we working on project
- [ ] Our team
- [ ] How to contribute
- [ ] Support us (Add Doika 1.2 module here)
- [ ] Partners
- [ ] Contact us (Add embedded google map here)
- [ ] Footer

**Comment by svetit** [comment]
@fr0zen Please, change
"Contact us (Add embedded google map here)" to "Contact us (Add embedded openstreetmap here)"

**Comment by svetit** [comment]
Prototype in figma https://www.figma.com/file/XLHeFtj7qOv0G3J8Eh1EeYWK/Mapa?node-id=0%3A1

Font: PT Sans
Links: underlined text.

Use Mapa brandbook for logo and colors: https://wiki.falanster.info/wiki/Брэнд_Мапы_заўтрашняга_дня

Red line means that there is a border for all content.

Here is the desktop version.
The pad and smartphone can be created in the easiest way using all pictures. (just rearrange them vertical).
Anyway I will test and send visual bugs to front-ender:)

**Comment by fr0zen** [comment]
@svetit changed, thanks for attention.

**Comment by svetit** [comment]
@Sannnao Hello. Have you explored this task? Do you have questions?

**Comment by svetit** [comment]
@Sannnao  We make a fork og KVM (Karte von morgen) and change landing page. This task is about that.
Here is karte von morgen https://kartevonmorgen.org/

**Comment by svetit** [comment]
@fr0zen  please, assign yourself to the task, because you do it.
And give a link where I can see the result of markup and test it.

**Comment by fr0zen** [comment]
@fr0zen add link to landing here on falanster domain
