### ISSUE TITLE
Events don't appear on map

### ISSUE THREAD

**Issue by ArtyomKr** [diglabby/mapa#382]
Events don't show up on our map. In kvm they work. 
It was noticed by https://github.com/diglabby/mapa/issues/162#issuecomment-642767331 . Some examples: 
**kvm**:
![image](https://user-images.githubusercontent.com/53486579/85575277-18e45200-b640-11ea-8f6f-b037e2d686b4.png)
**mapa**:
![image](https://user-images.githubusercontent.com/53486579/85575384-2ef21280-b640-11ea-8d76-37470714efba.png)
Can it be related to https://github.com/diglabby/mapa/issues/162#issuecomment-640048844?

**Comment by rizomaa** [comment]
@ArtyomKr I assign the issue to you. This has high priority now. 

It correlates with https://github.com/diglabby/mapa/issues/162

**Comment by ArtyomKr** [comment]
I think I found what was causing this problem by comparing kvm and mapa GET requests. 
It's the time. Mapa requests server to find events from today while kvm requests events from 1970 (basically all events that ever existed). It's very strange that kvm works but mapa doesn't. Here is the quick comparison: 

**Mapa GET events request:**
![image](https://user-images.githubusercontent.com/53486579/86912919-7c817b80-c126-11ea-8f11-56e128e3796f.png)

Time is set to `1594155600000` ms that's Wed 8 July 2020 00:00:00 (today). Mapa requests events from today onwards.

**Kvm GET events request:**
![image](https://user-images.githubusercontent.com/53486579/86914747-79d45580-c129-11ea-9a81-8ad9a4cb0c9b.png)

Time is `1594166400` ms, that's Mon 19 January 1970 13:49:26. Kvm requests all events.

**Comment by ArtyomKr** [comment]
I finally understood: kvm uses date in seconds while mapa uses it in milliseconds. `1594166400` seconds in kvm is Wednesday, 8 July 2020 г., 0:00:00, so it's right.

**Comment by rizomaa** [comment]
@ArtyomKr дзякуй за працу. ПР прыняты)
