### ISSUE TITLE
[Developer] Write translations

### ISSUE THREAD

**Issue by fr0zen** [diglabby/mapa#39]
Set translation text inside https://github.com/diglabby/mapa/tree/master/src/locales/translation-be.json as example will be https://github.com/diglabby/mapa/blob/master/src/locales/translation-en.json
Text changed in sections
- [ ] Top menu
- [ ] Mapa applications from KVM
- [ ] Аbout us section
- [ ] Goals
- [ ] For who
- [ ] Principles
- [ ] How we working on project
- [ ] Our team
- [ ] How to contribute
- [ ] Support us (Add Doika 1.2 module here)
- [ ] Partners
- [ ] Contact us (Add embedded google map here)
- [ ] Footer

**Comment by yurykim87** [comment]
File does not exist:
https://github.com/diglabby/mapa/tree/master/src/locales/translation-be.json

**Comment by fr0zen** [comment]
@yurykim87 then it up to you to create it :) As example you may take https://github.com/diglabby/mapa/blob/master/src/locales/translation-en.json

**Comment by rizomaa** [comment]
https://github.com/diglabby/mapa/issues/1
https://github.com/diglabby/mapa/issues/5
related tasks
