### ISSUE TITLE
[2] operate only with events and initiatives (hide enterprises)

### ISSUE THREAD

**Issue by rizomaa** [diglabby/mapa#4]
- [ ] In current installation we should hide "Enterprise" functionality.

**Comment by fr0zen** [comment]
- [ ] Think, what mechanism we use to define type of initiative (non-profit/Enterprise).

**Comment by rizomaa** [comment]
@fr0zen there is a mechnism of tags where you can add tag characterising particular initiative? Or you mean something else?

**Comment by fr0zen** [comment]
@rizomaa yes, "non-profit" or "enterprise" tag will be added during organisation/event creation process by themselves. Maybe in future we can add some moderation functionality here.

**Comment by wellemut** [comment]
Untill now, enterprise does not decide between for-profit and not-for profit, it just indicates, that you get a certain service there.
If you want to hide it in General from your users, I am fearing, that thy will add ethical and social businesses just as initiatives, which would make it unpossible to distinguish later.

Activly ask the user, if its for-profit or no-profit could be a solution, but is that really the most important question to ask? Others would think that veganism, renewable engergies... would be much more important.
Lets discuss this during Hackathon...

**Comment by rizomaa** [comment]
@wellemut we've already discussed that " ethical and social businesses" we will be in our focus later. 

Because they are different audience and we have limited sources to make qualitative outreach simultaneously. Don't get me wrong, your point is good and we have ideas how to work with the audience but step by step. 

And may be you know that provide very broad service on initial steps is not always efficient in term of cooperation.

**Comment by wellemut** [comment]
Maybe the best way would be to just deactivate enterprise by default. Same as we have deactivated events at the moment. 
So when users want to add an enterprise, they can do and dont need to define it wrongly as initiative, but we promote only initiatives by default.

I would move this issue to the "mapathon" first for strategic discussions, before we do any changes at the frontend.
