### ISSUE TITLE
[Developer] Change  Footer section according new layout and content

### ISSUE THREAD

**Issue by fr0zen** [diglabby/mapa#55]
https://github.com/diglabby/mapa/blob/194d4bf7edc43815dfea781f4b96c5f62c70e9ff/src/components/LandingPage.jsx#L339
Design https://www.figma.com/file/XLHeFtj7qOv0G3J8Eh1EeYWK/Mapa?node-id=0%3A1
https://github.com/diglabby/mapa/tree/master/src/locales - localization files

**Comment by fr0zen** [comment]
@entropia please provide social links to the:
- [ ] fb
- [ ] vk
- [ ] github
- [ ] telegram
and license links 
- [ ] CC-BY-CA

**Comment by svetit** [comment]
@fr0zen do you need link to the licence?
