### ISSUE TITLE
[1][1] Merge final translation array for belarussian version

### ISSUE THREAD

**Issue by fr0zen** [diglabby/mapa#59]
- [ ] Get actual be translation by [link](https://github.com/diglabby/mapa/files/3388744/BYloc.be.zip)
- [ ] Merge actual file https://github.com/diglabby/mapa/blob/develop/src/locales/translation-by.json with be translation file provided by previous link.

Result translation file must contain all translations on landing + translations on application.

**Comment by rizomaa** [comment]
@fr0zen @antos-k тут зачыняем?
