### ISSUE TITLE
[5] get iframe-code from a map view

### ISSUE THREAD

**Issue by rizomaa** [diglabby/mapa#7]
As a administrator of other websites, I want to get code for an embedded widget from a map page
Embedded widget can help to show information

- [ ] by tag
- [ ] by initative
- [ ] width
- [ ] height
- [ ] borders
- [ ] show only events
- [ ] show only organisations
- [ ] Select specific organisation with original color or mark
- [ ] Show only proprietary
- [ ] Show only non-profit

**Comment by fr0zen** [comment]
- [ ] Define, how we provide final link to users.
- [ ] Decide changeable parameters of iframe.
- [ ] Develop iframe link generator.

**Comment by rizomaa** [comment]
@fr0zen what are the "changeable parameters"?

**Comment by fr0zen** [comment]
@rizomaa it's parameters like width, height, borders, show only events, or show only organisations.

**Comment by wellemut** [comment]
Here is this issue on kvm repo https://github.com/goodmap/goodmap-old/issues/512

I would let the user select the content and filters directly on kvm. In the iframe Generator the user just needs to define

- [ ] width
- [ ] height
- [ ] borders

**Comment by rizomaa** [comment]
@wellemut if the task partially done, we can add more functionality through URL

**Comment by rizomaa** [comment]
@wellemut 

I've just read the article with google translation http://blog.vonmorgen.org/iframes/. There are several points in the article I need you translate.

1. Does "Search" work only with one word? Is it possible to use several different key words?
2. How to find a hash for each "entry" there?
3. Why do you use a different domain in ifframe src "mapofmorgen.org" ? not https://kartevonmorgen.org if we want to implement on our domain, what should it be there?

**Comment by wellemut** [comment]
Hi @rizomaa 
I think some of your question result of google bads translation, but here you have the same article in english: https://blog.vonmorgen.org/en/iframes-2/

You can add several word to the searchline, just try:
    You can just add several word in the searchline and they will be linke as OR connection which means, that you get all entries, where one of the keywords match.
    If you add severay tags with # in the searchline, it is an AND connection. That means you get only thos entries, where all tags match.

**Comment by wellemut** [comment]
Hi @rizomaa 
This function, as it is deployed on https://mapa.falanster.by/#map seems to be working very well.
Is there still somebody working on it or can we pull it to kartevonmorgen.org (https://github.com/kartevonmorgen/kartevonmorgen/issues/512)

**Comment by JustOneJance** [comment]
Hi, no, this function in work process. But i'm really sorry, i leave from
my job. And we open new company, and i don't have time for finish this
task. But i trying find time for it.

чт, 10 окт. 2019 г. в 23:02, Helmut Wolman <notifications@github.com>:

**Comment by rizomaa** [comment]
@JustOneJance any updates, or to move the task to other contributors?

**Comment by wellemut** [comment]
@JustOneJance and @rizomaa 
I can ask our Developers, if they can finish it/work on it.

the iframe-code-Generator seems to be completey ready. Could you please link the merge-request here, so that we can use it?
