### ISSUE TITLE
Add openfair.db and (TBD) webpack.config.babel.js and URLs.js  to .gitignore

### ISSUE THREAD

**Issue by antos-k** [diglabby/mapa#70]
We have next steps in installation guide https://github.com/diglabby/mapa/wiki/Installation-guide-(by-rizomaa) :

> 3. Seed some content to the DB by getting the file from the archive https://github.com/flosse/openfairdb/files/2511314/openfair.db.zip and unpack it in `<project-name>` **directory**
> ...
> 5. Change the [file](https://github.com/goodmap/goodmap-old/pull/583/commits/b5d967c752df4b2e138e30fdbeb7101b5354be1c) `webpack.config.babel.js` and [this](https://github.com/goodmap/goodmap-old/pull/583/commits/57cb6aa7bfe590130b93ed1236b7bf88ee8dac1a) `src/constants/URLs.js` by following appropriate commits are under links.
> 

**Issue:** Now this files are not in **.gitignore**, so it will be rewrited (and our local data will be lost!) during version updates from git.
**Expected result**: 
Add **openfair.db**, and (to be discussed) **webpack.config.babel.js** and **src/constants/URLs.js**  to .gitignore

**Comment by rizomaa** [comment]
@fr0zen any thoughts?
