### ISSUE TITLE
[4][8] To create Unsubscription (is this Hash field)?

### ISSUE THREAD

**Issue by rizomaa** [diglabby/mapa#92]

**Comment by uklotzde** [comment]
Currently only a single subscription is supported by openfairdb. Multiple subscriptions for the same user could only be distinguished by their bbox coordinates.

I would recommend to make a proposal of how the new `/subscriptions` REST-API could look like. Use OpenAPI/Swagger for this purpose. From this starting point we could then think about how to extend the domain model and the database schema.
